"""initiales schema

Revision ID: 5c89ad6296c1
Revises: 
Create Date: 2026-08-16 11:33:22.090921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c89ad6296c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profil_text', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('passwort_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chat_nachrichten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutzer_id', sa.Integer(), nullable=True),
    sa.Column('rolle', sa.String(), nullable=True),
    sa.Column('inhalt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nutzer_id'], ['nutzer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutzer_id', sa.Integer(), nullable=True),
    sa.Column('job_titel', sa.String(), nullable=True),
    sa.Column('richtung', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nutzer_id'], ['nutzer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swipes')
    op.drop_table('chat_nachrichten')
    op.drop_table('nutzer')
    # ### end Alembic commands ###
